version: "3"
services:
  app:
    env_file:
      - .env
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py flush --no-input &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"
