# Generated by Django 4.0.4 on 2022-05-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('label', models.CharField(max_length=80, verbose_name='Label')),
                ('kind', models.CharField(choices=[('video', 'Vidéo'), ('audio', 'Audio'), ('photo', 'Photo'), ('misc', 'Divers')], default='video', max_length=5, verbose_name='Type')),
                ('file', models.FileField(upload_to='media/', verbose_name='Fichier')),
            ],
            options={
                'verbose_name': 'Référence',
                'verbose_name_plural': 'Références',
            },
        ),
    ]
